### ISSUE TITLE
How to programmatically apply 'align face'

### ISSUE THREAD

**Issue by arloporter** [KeenTools/keentools-blender#163]
Hello,
I am trying to programmatically control the facebuilder process from start to finish. So far, from looking at the codebase, i have managed to create a head, load images, add pins, bake the texture (after manual alignment) and create blendshapes. I cant seem to use the 'align face' feature.

Here is my code:

`def prepare_head():
    settings = get_main_settings()
    
    try:
        bpy.ops.keentools_facebuilder.add_head()
    except RuntimeError:    
        bpy.ops.keentools_facebuilder.reconstruct_head()
        
    obj = bpy.context.object
    settings.fix_heads()
    headnum = len(settings.heads)
    
    face_path= './faceimages/'
    fb = FBLoader.new_builder()
    params = cameras.get_camera_params(obj)
    if params is None:
        params = cameras.default_camera_params()
    
    override_context = bpy.context.copy()
    area = [area for area in bpy.context.screen.areas if area.type == "VIEW_3D"][0]
    override_context['window'] = bpy.context.window
    override_context['screen'] = bpy.context.screen
    override_context['area'] = area
    override_context['region'] = area.regions[-1]
    override_context['scene'] = bpy.context.scene
    override_context['space_data'] = area.spaces.active
    
    count = 0 
    for i in os.listdir(face_path):
        FBLoader.add_new_camera_with_image(0, face_path + i)
        bpy.ops.keentools_facebuilder.pinmode(override_context, 'INVOKE_DEFAULT', headnum=0, camnum=count)
        bpy.ops.keentools_facebuilder.pickmode(override_context, 'EXEC_DEFAULT', headnum=0, camnum=count)
        count +=1
        
    FBLoader.update_cameras_from_old_version(0)
    bpy.ops.keentools_facebuilder.bake_tex()
    bpy.ops.keentools_facebuilder.create_blendshapes()`

The problems i keep facing seem to be regarding keyframes not being specified and 'rectangular index not specified'

`2022-09-18 18:12:29,659 - keentools_facebuilder.pinmode - ERROR -
UNKNOWN KEYFRAME: 1`

`'No selected rectangle index'`

Is there a proper way to do this?

**Comment by SergeyKrivohatskiy** [comment]
Hi!
It's not intended for keentools blender addon to be used via python scripts. It's a GUI only way to work with FaceBuilder. Of course you may try to manipulate FaceBuilder in blender via python, but we won't help you with this.

You may try working with pykeentools (keentools-core) module directly. Here are some tutorials on this https://github.com/KeenTools/keentools-core-tutorials. For example there is a separate tutorial for automatic face reconstruction with FaceBuilder. Please also check licensing options for pykeentools.
