### ISSUE TITLE
Is this a trail version of facebuilder addon or lifetime validity liscence?

### ISSUE THREAD

**Issue by sanatmalani** [KeenTools/keentools-blender#88]
We want to use this for educational purposes so we are looking for a GPL version of face builder Kentools for Blender.

Thanks.

**Comment by SergeyKrivohatskiy** [comment]
The Blender addon itself is under GPL v3.0. It's sources are available in this repository. 
The KeenTools core python library (addon is designed to use) is a proprietary software. It is not using any of the GPL licensed codebase. You may write to team@keentools.io to get more information.

You may request educational licenses for KeenTools FaceBuidler via your school. See https://keentools.io/schools for more information.
